language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

script:
  - composer create-project --prefer-dist laravel/laravel laravel_test
  - cd laravel_test
  - composer require pingcheng/slack-slash-command
  - php artisan vendor:publish --provider="PingCheng\SlackSlashCommand\SlackSlashCommandServiceProvider"
  - cd vendor
  - cd pingcheng
  - cd slack-slash-command
  - php ../../../vendor/bin/phpunit --coverage-text
  - php vendor/bin/php-coveralls -v